# Author: Joris Rietveld <jorisrietveld@gmail.com>
# Created: 05-08-2017 07:05
# Licence: GPLv3 - General Public Licence version 3
public:
    resource: '@AppBundle/Resources/config/routing/public.yml'

private:
    resource: '@AppBundle/Resources/config/routing/private.yml'

admin:
    resource: '@AppBundle/Resources/config/routing/public.yml'

