# Author: Joris Rietveld <jorisrietveld@gmail.com>
# Created: 16-07-2017 12:41
# Licence: GPLv3 - General Public Licence version 3

camping:
    path:     /camping
    defaults: { _controller: AppBundle:Camping:camping }