# Author: Joris Rietveld <jorisrietveld@gmail.com>
# Created: 16-07-2017 12:43
# Licence: GPLv3 - General Public Licence version 3

facilities:
    path:     /fasaliteiten
    defaults: { _controller: AppBundle:Facilities:facilities }
