# Author: Joris Rietveld <jorisrietveld@gmail.com>
# Created: 16-07-2017 12:41
# Licence: GPLv3 - General Public Licence version 3

default:
    path: /
    defaults: { _controller: AppBundle:Home:home }

#home:
#    path:     /home
#    defaults: { _controller: AppBundle:Home:home }


#
# Code mobile phone.
# Zwaluw staart plaat merk: lewis - naam: plancher
# Pose plancher metallique
# Pin mobile: 4236
#
