# Author: Joris Rietveld <jorisrietveld@gmail.com>
# Created: 05-08-2017 06:58
# Licence: GPLv3 - General Public Licence version 3

#########################################################################################################[ Home Routes]
# This route leads to the home page welcome fragment.
default:
    path: /
    defaults:
        _controller: 'AppBundle:Home:home'
        _fragment: 'page-top'

# This route leads to the home page about fragment.
about:
    path: /
    defaults:
        _controller: 'AppBundle:Home:home'
        _fragment: about

# This route leads to the home page route fragment.
route:
    path: /
    defaults:
        _controller: 'AppBundle:Home:home'
        _fragment: route

# This route leads to the home page contact fragment.
contact:
    path: /
    defaults:
        _controller: 'AppBundle:Home:home'
        _fragment: contact
#####################################################################################################[ Edition Routes ]
# This route leads to an events index page where you can select the year you want to see.
editions:
    path: /editions
    defaults:
        _controller: 'AppBundle:Home:home'

# This route leads to an individual event index page by year.
edition:
    path: /edition/{year}
    defaults:
        _controller: 'AppBundle:Home:home'

########################################################################################################[ Band Routes ]
# This route leads to the bands index page.
bands:
    path: /bands
    defaults:
        _controller: 'AppBundle:Home:home'

# This route leads to an individual band that played at wedderheide.
band:
    path: /band/{year}
    defaults:
        _controller: 'AppBundle:Home:home'

############################################################################[ Authentication and authorization Routes ]
# This route leads to the login page for.
login:
    path: /login
    defaults:
        _controller: 'AppBundle:Home:home'

# This route leads to the registration page.
register:
    path: /register
    defaults:
        _controller: 'AppBundle:Home:home'
