# Author: Joris Rietveld <jorisrietveld@gmail.com>
# Created: 05-08-2017 06:58
# Licence: GPLv3 - General Public Licence version 3

#########################################################################################################[ Home Routes]
# This route leads to the home page welcome fragment.
default:
    path: /
    defaults:
        _controller: 'AppBundle:Home:home'
        _fragment: 'page-top'
        linkTranslationKey: 'navigation.home.title'

# This route leads to the home page about fragment.
about:
    path: '/'
    defaults:
        _controller: 'AppBundle:Home:home'
        _fragment: 'about'
        linkTranslationKey: 'navigation.home.submenu.about'
        parent: 'default'

# This route leads to the home page route fragment.
route:
    path: '/'
    defaults:
        _controller: 'AppBundle:Home:home'
        _fragment: 'route'
        linkTranslationKey: 'navigation.home.submenu.route'
        parent: 'default'

# This route leads to the home page contact fragment.
contact:
    path: '/'
    defaults:
        _controller: 'AppBundle:Home:home'
        _fragment: 'contact'
        linkTranslationKey: 'navigation.home.submenu.contact'
        parent: 'default'

#####################################################################################################[ Edition Routes ]
# This route leads to an events index page where you can select the year you want to see.
editions:
    path: '/editions'
    defaults:
        _controller: 'AppBundle:Event:events'
        linkTranslationKey: 'navigation.editions.title'
        _fragment: 'page-top'

# This route leads to an individual event index page by year.
edition:
    path: '/edition/{year}'
    defaults:
        _controller: 'AppBundle:EventController:event'
        linkTranslationKey: 'navigation.edition.title'
        parent: 'editions'
        year: 'default'

########################################################################################################[ Band Routes ]
# This route leads to the bands index page.
bands:
    path: '/bands'
    defaults:
        _controller: 'AppBundle:Band:bands'
        linkTranslationKey: 'navigation.bands.title'
        _fragment: 'page-top'

# This route leads to an individual band that played at wedderheide.
band:
    path: '/band/{bandName}'
    defaults:
        _controller: 'AppBundle:Band:band'
        linkTranslationKey: 'navigation.bands.title'
        parent: 'bands'
        bandName: 'default'

agenda:
    path: '/agenda'
    defaults:
        _controller: 'AppBundle:Home:home'
        linkTranslationKey: 'navigation.agenda.title'
        _fragment: 'page-top'

############################################################################[ Authentication and authorization Routes ]
# This route leads to the login page for.
login:
    path: '/login'
    defaults:
        _controller: 'AppBundle:Authentication:login'
        linkTranslationKey: ''

# This route leads to the registration page.
register:
    path: '/register'
    defaults:
        _controller: 'AppBundle:Authentication:register'
        linkTranslationKey: ''
