# Author: Joris Rietveld <jorisrietveld@gmail.com>
# Created: 16-07-2017 12:42
# Licence: GPLv3 - General Public Licence version 3

surrounding:
    path:     /omgeving
    defaults: { _controller: AppBundle:Surrounding:surrounding }
