AppBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        subject:
            type: string
            length: 255
        email:
            type: string
            length: 255
        message:
            type: text
        userId:
            type: integer
            nullable: true
        country:
            type: string
            length: '50'
            nullable: true
    lifecycleCallbacks: {  }
